const $=s=>document.querySelector(s);
const STORAGE_KEY='ambikaSalonCustomersV1';
const APPT_KEY='ambikaSalonAppointmentsV1';
const STAFF_KEY='ambikaSalonStaffStatusV1';
const STAFF=[
 {id:'balaji',name:'Balaji Vaidya',photo:'assets/balaji-vaidya.jpg'},
 {id:'dnyanoba',name:'Dnyanoba Vaidya',photo:'assets/dnyanoba-vaidya.jpg'},
 {id:'nikhil',name:'Nikhil Vaidya',photo:'assets/nikhil-vaidya.jpg'}
];
const SERVICES=[
 ['Haircut — Simple',150],['Haircut — Style',170],['Clean Shave',80],['Style Beard',100],['D-Tan',500],['Hair Spa',700],['Bleach',300],['Hair Tonic',150],['Hair Massage',150],['Chappi',150],['Cutline',120],['Small Girls Hair Cut',200],['Begain Colour',650],['Garnier / L\'Oreal',350],['Hair Shampoo',60],['Fresh',50],['Mustage Colour',30],['Face Massage — Simple',250],['Spa Massage',450],['Charcol Mask',300],['Face Scrub',200],['Powder Hairdry',200],['Face, Head Steam',200]
];
function todayISO(){const d=new Date();d.setHours(0,0,0,0);return d.toISOString().slice(0,10)}
function addDays(dateStr,days){const d=new Date(dateStr+'T00:00:00');d.setDate(d.getDate()+Number(days));return d.toISOString().slice(0,10)}
function fmt(dateStr){return new Date(dateStr+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function loadCustomers(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch(e){return []}}
function saveCustomers(list){localStorage.setItem(STORAGE_KEY,JSON.stringify(list))}
function loadAppointments(){try{return JSON.parse(localStorage.getItem(APPT_KEY)||'[]')}catch(e){return []}}
function saveAppointments(list){localStorage.setItem(APPT_KEY,JSON.stringify(list))}
function loadStaffStatus(){try{return {...Object.fromEntries(STAFF.map(s=>[s.id,'available'])),...JSON.parse(localStorage.getItem(STAFF_KEY)||'{}')}}catch(e){return Object.fromEntries(STAFF.map(s=>[s.id,'available']))}}
function saveStaffStatus(x){localStorage.setItem(STAFF_KEY,JSON.stringify(x))}
function normalPhone(phone){let p=String(phone||'').replace(/\D/g,'');if(p.startsWith('0'))p=p.slice(1);if(p.length===10)p='91'+p;return p}
function reminderMessage(c){return `Hello ${c.name}, this is Ambika Hair Salon, Beed. It has been ${c.days} days since your last ${c.service.toLowerCase()} visit. Would you like to book your next appointment? Reply here and we will help you choose a time. Thank you!`}
function status(c){const t=todayISO();if(c.reminderDate<t)return 'overdue';if(c.reminderDate===t)return 'due';return 'upcoming'}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function render(){
 const list=loadCustomers().sort((a,b)=>a.reminderDate.localeCompare(b.reminderDate));
 const q=($('#searchCustomers')?.value||'').toLowerCase().trim();
 const filtered=list.filter(c=>`${c.name} ${c.phone} ${c.service}`.toLowerCase().includes(q));
 const due=list.filter(c=>['due','overdue'].includes(status(c))).length;
 const upcoming=list.filter(c=>status(c)==='upcoming').length;
 if($('#totalCustomers'))$('#totalCustomers').textContent=list.length;if($('#dueCustomers'))$('#dueCustomers').textContent=due;if($('#upcomingCustomers'))$('#upcomingCustomers').textContent=upcoming;
 if($('#emptyReminders'))$('#emptyReminders').style.display=filtered.length?'none':'block';
 if($('#reminderList'))$('#reminderList').innerHTML=filtered.map(c=>{const st=status(c);const tag=st==='due'?'Due today':st==='overdue'?'Overdue':`Due ${fmt(c.reminderDate)}`;return `<div class="reminder-item ${st}"><div><h4>${escapeHtml(c.name)}</h4><p>${escapeHtml(c.service)} • ${escapeHtml(c.phone)}</p><p>Visit: ${fmt(c.visitDate)} • Reminder: <span class="date">${fmt(c.reminderDate)}</span></p>${c.notes?`<p>Note: ${escapeHtml(c.notes)}</p>`:''}<span class="tag ${st}">${tag} • ${c.days} days</span></div><div class="reminder-actions"><button class="wa-small" data-wa="${c.id}">WhatsApp</button><button class="done-small" data-done="${c.id}">Done</button><button class="delete-small" data-delete="${c.id}">Delete</button></div></div>`}).join('');
 renderStaff();renderAppointments();updateBookingOptions();
}
function timeSlots(){const a=[];for(let m=8*60+30;m<=22*60+30;m+=30){const h=Math.floor(m/60),min=m%60;a.push(`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`)}return a}
function isBooked(staff,date,time){return loadAppointments().some(a=>a.staffId===staff&&a.date===date&&a.time===time&&a.status!=='cancelled')}
function timeToMinutes(t){const [h,m]=String(t).split(':').map(Number);return h*60+m}
function getLiveAppointment(staffId){const now=new Date(),date=todayISO();const mins=now.getHours()*60+now.getMinutes();return loadAppointments().find(a=>a.staffId===staffId&&a.date===date&&a.status!=='cancelled'&&mins>=timeToMinutes(a.time)&&mins<timeToMinutes(a.time)+30)||null}
function getNextAppointment(staffId){const now=new Date(),date=todayISO(),mins=now.getHours()*60+now.getMinutes();return loadAppointments().filter(a=>a.staffId===staffId&&a.date===date&&a.status!=='cancelled'&&timeToMinutes(a.time)>mins).sort((a,b)=>timeToMinutes(a.time)-timeToMinutes(b.time))[0]||null}
function staffDisplayStatus(staffId){const manual=loadStaffStatus()[staffId]||'available';if(manual==='on leave')return {key:'leave',label:'On Leave'};if(manual==='on job')return {key:'job',label:'On Job'};if(getLiveAppointment(staffId))return {key:'appt',label:'In Appointment'};return {key:'available',label:'Available'}}
function renderStaff(){const box=$('#staffStatusGrid');if(!box)return;const states=loadStaffStatus();box.innerHTML=STAFF.map(s=>{const manual=states[s.id]||'available';const live=getLiveAppointment(s.id);const next=getNextAppointment(s.id);const disp=staffDisplayStatus(s.id);return `<article class="status-card"><img src="${s.photo}" alt="${s.name} profile"><h3>${s.name}</h3><p>All 23 salon services</p><span class="status-pill ${disp.key}">${disp.label}</span>${live?'<p class="live-note">Currently serving a customer</p>':next?`<p class="next-note">Next appointment: ${escapeHtml(next.time)}</p>`:'<p class="next-note">No appointment right now</p>'}<select class="status-select" data-status="${s.id}"><option value="available" ${manual==='available'?'selected':''}>Available</option><option value="on job" ${manual==='on job'?'selected':''}>On Job</option><option value="on leave" ${manual==='on leave'?'selected':''}>On Leave</option></select></article>`}).join('')}
function renderAppointments(){const date=$('#scheduleDate')?.value||todayISO();const list=loadAppointments().filter(a=>a.date===date&&a.status!=='cancelled').sort((a,b)=>a.time.localeCompare(b.time));if($('#emptyAppointments'))$('#emptyAppointments').style.display=list.length?'none':'block';if(!$('#appointmentList'))return;$('#appointmentList').innerHTML=list.map(a=>`<div class="appointment-item"><div><h4>${escapeHtml(a.time)} · ${escapeHtml(a.service)}</h4><p><strong>${escapeHtml(a.staffName)}</strong> · ${escapeHtml(a.name)} · ${escapeHtml(a.phone)}</p><p>${escapeHtml(a.location)} · Total ₹${a.total}${a.notes?` · ${escapeHtml(a.notes)}`:''}</p></div><div class="appointment-actions"><button class="wa-small" data-appt-wa="${a.id}">WhatsApp</button><button class="delete-small" data-appt-delete="${a.id}">Cancel</button></div></div>`).join('')}
function updateBookingOptions(){const staffSel=$('#bookingStaff'),timeSel=$('#bookingTime'),date=$('#bookingDate')?.value||todayISO();if(staffSel){const states=loadStaffStatus();const current=staffSel.value;staffSel.innerHTML='<option value="">Select professional</option>'+STAFF.map(s=>{const manual=states[s.id]||'available';const live=date===todayISO()&&getLiveAppointment(s.id);const unavailable=manual!=='available';const label=manual==='on leave'?'On Leave':manual==='on job'?'On Job':live?'In Appointment':'Available';return `<option value="${s.id}" ${unavailable?'disabled':''}>${s.name} — ${label}</option>`}).join('');if(STAFF.some(s=>s.id===current&&states[s.id]==='available'))staffSel.value=current}if(timeSel){const staff=staffSel?.value;timeSel.innerHTML='<option value="">Select time</option>'+timeSlots().map(t=>{const booked=staff&&isBooked(staff,date,t);return `<option value="${t}" ${booked?'disabled':''}>${t}${booked?' — Booked':''}</option>`}).join('')}}
function updateTotal(){const opt=$('#bookingService')?.selectedOptions[0],base=Number(opt?.dataset.price||0),home=document.querySelector('input[name="location"]:checked')?.value==='Home Service';if($('#bookingTotal'))$('#bookingTotal').textContent='₹'+(home?base*2:base)}
$('#y').textContent=new Date().getFullYear();
if($('#cDate'))$('#cDate').value=todayISO();
if($('#bookingDate'))$('#bookingDate').value=todayISO();
if($('#scheduleDate'))$('#scheduleDate').value=todayISO();
$('#form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const staff=STAFF.find(s=>s.id===f.get('staff'));const states=loadStaffStatus();const time=f.get('time');const date=f.get('date');if(!staff||states[staff.id]!=='available')return alert('Please choose a professional who is currently Available.');if(isBooked(staff.id,date,time))return alert('That professional is already booked at this time. Please choose another time or professional.');const opt=$('#bookingService').selectedOptions[0];const base=Number(opt.dataset.price||0),home=f.get('location')==='Home Service',total=home?base*2:base;const appt={id:Date.now().toString(),name:String(f.get('name')).trim(),phone:String(f.get('phone')).trim(),staffId:staff.id,staffName:staff.name,service:String(f.get('service')),location:String(f.get('location')),date,time,total,notes:String(f.get('notes')||'').trim(),status:'booked',createdAt:new Date().toISOString()};const list=loadAppointments();list.push(appt);saveAppointments(list);const msg=`Hello Ambika Hair Salon!\n\nAppointment request/booking:\nCustomer: ${appt.name}\nPhone: ${appt.phone}\nProfessional: ${appt.staffName}\nService: ${appt.service}\nType: ${appt.location}\nDate: ${appt.date}\nTime: ${appt.time}\nTotal: ₹${appt.total}\nNote: ${appt.notes||'None'}\n\nPlease confirm the appointment.`;window.open('https://wa.me/919765634194?text='+encodeURIComponent(msg),'_blank');alert(`Appointment saved for ${appt.staffName} at ${appt.time}. Total: ₹${appt.total}`);e.target.reset();$('#bookingDate').value=todayISO();updateTotal();updateBookingOptions();renderAppointments()});
$('#bookingService')?.addEventListener('change',updateTotal);document.querySelectorAll('input[name="location"]').forEach(x=>x.addEventListener('change',updateTotal));
$('#bookingStaff')?.addEventListener('change',updateBookingOptions);$('#bookingDate')?.addEventListener('change',updateBookingOptions);$('#scheduleDate')?.addEventListener('change',renderAppointments);
$('#staffStatusGrid')?.addEventListener('change',e=>{const id=e.target.dataset.status;if(!id)return;const states=loadStaffStatus();states[id]=e.target.value;saveStaffStatus(states);updateBookingOptions();renderStaff()});
setInterval(()=>{updateBookingOptions();renderStaff();renderAppointments()},30000);
$('#appointmentList')?.addEventListener('click',e=>{const wa=e.target.dataset.apptWa,del=e.target.dataset.apptDelete;let list=loadAppointments();if(wa){const a=list.find(x=>x.id===wa);if(a){const msg=`Hello ${a.name}, this is Ambika Hair Salon. Your appointment is with ${a.staffName} for ${a.service} on ${fmt(a.date)} at ${a.time}. Type: ${a.location}. Total: ₹${a.total}. Thank you!`;window.open('https://wa.me/'+normalPhone(a.phone)+'?text='+encodeURIComponent(msg),'_blank')}}if(del){if(confirm('Cancel this appointment?')){list=list.map(a=>a.id===del?{...a,status:'cancelled'}:a);saveAppointments(list);renderAppointments();updateBookingOptions()}}});
$('#clearAppointments')?.addEventListener('click',()=>{if(confirm('Clear all appointments saved in this browser?')){localStorage.removeItem(APPT_KEY);render()}});
$('#customerForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),days=Number(f.get('days')),c={id:Date.now().toString(),name:String(f.get('name')).trim(),phone:String(f.get('phone')).trim(),service:String(f.get('service')),visitDate:String(f.get('date')),days,reminderDate:addDays(String(f.get('date')),days),notes:String(f.get('notes')||'').trim()};const list=loadCustomers();list.push(c);saveCustomers(list);e.target.reset();$('#cDate').value=todayISO();alert(`Saved. Reminder date: ${fmt(c.reminderDate)}`);render()});
$('#searchCustomers').addEventListener('input',render);$('#reminderList').addEventListener('click',e=>{const wa=e.target.dataset.wa,done=e.target.dataset.done,del=e.target.dataset.delete;let list=loadCustomers();if(wa){const c=list.find(x=>x.id===wa);if(c)window.open('https://wa.me/'+normalPhone(c.phone)+'?text='+encodeURIComponent(reminderMessage(c)),'_blank')}if(done){const c=list.find(x=>x.id===done);if(c){c.completedAt=new Date().toISOString();c.reminderDate='9999-12-31';saveCustomers(list);render()}}if(del){if(confirm('Delete this customer reminder?')){saveCustomers(list.filter(x=>x.id!==del));render()}}});
$('#clearAll').addEventListener('click',()=>{if(confirm('Delete all saved customer reminders from this browser?')){localStorage.removeItem(STORAGE_KEY);render()}});
$('#exportBtn').addEventListener('click',()=>{const data=JSON.stringify(loadCustomers(),null,2);const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ambika-customer-reminders.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
const dueOnOpen=loadCustomers().filter(c=>['due','overdue'].includes(status(c)));if(dueOnOpen.length){setTimeout(()=>{if(location.hash==='#reminders')alert(`${dueOnOpen.length} customer reminder${dueOnOpen.length>1?'s are':' is'} due. Open the Reminder List to contact them.`)},600)}
render();updateTotal();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
